USE [TestDB]
GO

/****** Object:  Table [dbo].[BankDetails]    Script Date: 12/31/2018 3:17:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BankDetails](
	[Branchname] [varchar](50) NOT NULL,
	[BranchAddress] [varchar](50) NOT NULL,
	[BranchIfscCode] [varchar](50) NOT NULL,
	[BankId] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_BankDetails] PRIMARY KEY CLUSTERED 
(
	[BankId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


